# Configuration file for Google Cloud Builds

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.',
           '-t', 'eu.gcr.io/$PROJECT_ID/reverse-proxy:$TAG_NAME',
           '-t', 'eu.gcr.io/$PROJECT_ID/reverse-proxy:$SHORT_SHA',
           '-t', 'eu.gcr.io/$PROJECT_ID/reverse-proxy:latest']

images:
  - 'eu.gcr.io/$PROJECT_ID/reverse-proxy:$TAG_NAME'
  - 'eu.gcr.io/$PROJECT_ID/reverse-proxy:$SHORT_SHA'
  - 'eu.gcr.io/$PROJECT_ID/reverse-proxy:latest'